/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 21:32:06 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Bike_ESTest extends Bike_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike("a", 0.0, point2D_Double0, "A");
      Bike bike1 = bike0.clone();
      assertEquals(1, bike0.getSeats());
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(75.0, bike0.getSpeed(), 0.01);
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(1, bike1.getSeats());
      assertEquals("a",bike1.getLicencePlate());
      assertEquals("a",bike0.getLicencePlate());
      assertEquals("A",bike1.getOwner());
      assertEquals("A",bike0.getOwner());



  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike("", 1455.48680908384, point2D_Double0, "");
      Bike bike1 = bike0.clone();
      assertEquals(1, bike0.getSeats());
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(1, bike1.getSeats());
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(75.0, bike0.getSpeed(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Trip trip0 = new Trip();
      Point2D.Double point2D_Double0 = trip0.getEnd();
      Bike bike0 = new Bike("", (-1.0), point2D_Double0, "Bike");
      bike0.addTrip(trip0);
      // Undeclared exception!
      try { 
        bike0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bike bike0 = null;
      try {
        bike0 = new Bike((Bike) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Bike", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Trip trip0 = new Trip();
      Point2D.Double point2D_Double0 = trip0.getEnd();
      Bike bike0 = new Bike("", (-1.0), point2D_Double0, "Bike");
      Bike bike1 = bike0.clone();
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(75.0, bike0.getSpeed(), 0.01);
      assertEquals(1, bike0.getSeats());
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(1, bike1.getSeats());
      assertEquals(0.9, bike1.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Trip trip0 = new Trip();
      Point2D.Double point2D_Double0 = trip0.getEnd();
      Bike bike0 = new Bike("", (-1.0), point2D_Double0, "Bike");
      Bike bike1 = new Bike(bike0);
      assertEquals(1, bike0.getSeats());
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(1, bike1.getSeats());
      assertEquals(75.0, bike0.getSpeed(), 0.01);
      assertEquals(0.9, bike0.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Bike bike0 = null;
      try {
        bike0 = new Bike("i", 3313.1642723099, (Point2D.Double) null, "Z");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Vehicle", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Bike bike0 = null;
      try {
        bike0 = new Bike();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
