/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 21:22:36 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Car_ESTest extends Car_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("E%bB(EvkbG3Taf(Dn", 3023.4061587, point2D_Double0, "E%bB(EvkbG3Taf(Dn");
      Car car1 = car0.clone();
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(4, car0.getSeats());
      assertEquals(4, car1.getSeats());
      assertEquals(65.0, car0.getSpeed(), 0.01);
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(1.5, car1.getPrice(), 0.01);
      assertEquals("E%bB(EvkbG3Taf(Dn",car0.getLicencePlate());
      assertEquals("E%bB(EvkbG3Taf(Dn",car1.getLicencePlate());
      assertEquals(3023.4061587,car0.getReliable(),0.0001);
      assertEquals(3023.4061587,car1.getReliable(),0.0001);

  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Trip trip0 = new Trip();
      Point2D.Double point2D_Double0 = trip0.getEnd();
      Car car0 = new Car((String) null, (-104.858), point2D_Double0, (String) null);
      Car car1 = car0.clone();
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(65.0, car0.getSpeed(), 0.01);
      assertEquals(1.5, car1.getPrice(), 0.01);
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(4, car0.getSeats());
      assertEquals(4, car1.getSeats());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Trip trip0 = new Trip();
      Point2D.Double point2D_Double0 = trip0.getEnd();
      Car car0 = new Car((String) null, (-104.858), point2D_Double0, (String) null);
      car0.addTrip(trip0);
      // Undeclared exception!
      try { 
        car0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("E%bB(EvkbG3Taf(Dn", 3023.4061587, point2D_Double0, "E%bB(EvkbG3Taf(Dn");
      // Undeclared exception!
      try { 
        car0.calculateTraffic((HashMap<String, Vehicle>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Car car0 = null;
      try {
        car0 = new Car("Jn<QzcW;", 1.0, (Point2D.Double) null, "Jn<QzcW;");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Vehicle", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Car car0 = null;
      try {
        car0 = new Car((Car) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("E%bB(EvkbG3Taf(Dn", 3023.4061587, point2D_Double0, "E%bB(EvkbG3Taf(Dn");
      Car car1 = new Car(car0);
      assertEquals(4, car1.getSeats());
      assertEquals(1.5, car1.getPrice(), 0.01);
      assertEquals(4, car0.getSeats());
      assertEquals(65.0, car0.getSpeed(), 0.01);
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(1.5, car0.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("wm8X<6ZDF#8,_Ct?7x", 0.0, point2D_Double0, "wm8X<6ZDF#8,_Ct?7x");
      Car car1 = car0.clone();
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(1.5, car1.getPrice(), 0.01);
      assertEquals(4, car0.getSeats());
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(4, car1.getSeats());
      assertEquals(65.0, car0.getSpeed(), 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Car car0 = null;
      try {
        car0 = new Car();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
