/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 21:29:13 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Driver_ESTest extends Driver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay(69, 2);
      Driver driver0 = new Driver("", "", (String) null, "", localDate0, 2.0, "p-EYtIxXkpj|sK4yFH");
      driver0.addRating(2);
      assertEquals(40.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay(69, 1);
      Driver driver0 = new Driver("", "", "", "", localDate0, 1352.0, "#.Ea");
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Trip trip0 = new Trip(3240, point2D_Double0, point2D_Double0, (Double) 0.0, (Double) 0.0, localDate0, "", "\nVe\u00EDculo : ", (String) null, 69, 0.0, point2D_Double0, 3240, 3240, (-127.0));
      driver0.addTrip(trip0);
      assertEquals(127.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Period period0 = Period.ZERO;
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("<", "<", "<", "\nVe\u00EDculo : ", localDate0, 1502.0, "<");
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Point2D.Double point2D_Double1 = new Point2D.Double((-525), (-1958.71));
      Trip trip0 = new Trip((-525), point2D_Double0, point2D_Double0, (Double) point2D_Double0.x, (Double) point2D_Double0.x, localDate0, "\nVe\u00EDculo : ", "\nPre\u00E7o estimado : ", "\nVe\u00EDculo : ", 0, 0.0, point2D_Double1, 1.0, 2.0, 0.0);
      driver0.addTrip(trip0);
      assertEquals(2027.8485801706202, driver0.getTotalDistance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      Driver driver0 = new Driver("", "", "", "Driver", localDate0, (-1L), "");
      assertTrue(driver0.isAvailable());
      
      Boolean boolean0 = new Boolean("");
      driver0.setAvailability(boolean0);
      driver0.isAvailable();
      assertEquals("", driver0.getCompany());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("", "", "", "", localDate0, 0L, "UJ");
      driver0.setVehicle("~N");
      driver0.getVehicle();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals("UJ", driver0.getCompany());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Period period0 = Period.ofYears(1224);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Boolean boolean0 = Boolean.TRUE;
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("m>(p:E:*Y)So", "", (String) null, "", localDate0, 1224, 1456.567488431, boolean0, (-438.489), arrayList0, (-1), 1456.567488431, (-1708.956081), "", "", 1224);
      String string0 = driver0.getVehicle();
      assertNotNull(string0);
      assertEquals((-1), driver0.getNumberOfReviews());
      assertEquals((-438.489), driver0.getTimeCompliance(), 0.01);
      assertEquals("", string0);
      assertEquals(1224.0, driver0.getDeviation(), 0.01);
      assertEquals("", driver0.getCompany());
      assertEquals(1456.567488431, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Period period0 = Period.ofWeeks((-1414));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("\neMail : ", "", "", "\neMail : ", localDate0, (-1414), "AQYK^0N%I");
      Double double0 = driver0.getTimeCompliance();
      assertEquals((-1414.0), (double)double0, 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals("AQYK^0N%I", driver0.getCompany());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      String string0 = "\\uKA$}Y\\=w50C:X_$hi";
      Driver driver0 = new Driver("Viagem de (", "Viagem de (", "lF/nJ", "\nVe\u00EDculo : ", localDate0, 269.417650127939, string0);
      driver0.setTimeCompliance(0.0);
      driver0.getTimeCompliance();
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2004L);
      Driver driver0 = new Driver("T#-", (String) null, "!kR3HdT:J.!Z^", "!kR3HdT:J.!Z^", localDate0, 2004L, (String) null);
      Double double0 = driver0.getTimeCompliance();
      assertTrue(driver0.isAvailable());
      assertEquals(2004.0, (double)double0, 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("xrd)Uxo*e?-q\"T_!+", "=#8?R1#+Tt7A;;Px", "xrd)Uxo*e?-q\"T_!+", "O<Lo}2!'H':WM]7\"K=", localDate0, 4.0, "xrd)Uxo*e?-q\"T_!+");
      driver0.setNumberOfReviews((-1));
      driver0.addRating((-1));
      driver0.getRating();
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("", "", "h:", "", localDate0, 399.615066471907, "");
      Double double0 = driver0.getRating();
      assertEquals(399.615066471907, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals("", driver0.getCompany());
      assertEquals(0.0, (double)double0, 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("", "hyf8L", "xj$", "hyf8L", localDate0, 0L, ";z");
      driver0.setRating(335.097269464);
      driver0.getRating();
      assertEquals(335.097269464, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("\nTrip id : ", "\nTrip id : ", "\nTrip id : ", "\nTrip id : ", localDate0, 0L, "3wz\",p#}!?[c{iV");
      driver0.addRating(0);
      int int0 = driver0.getNumberOfReviews();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      Driver driver0 = new Driver("", "", "", "Driver", localDate0, (-1L), "");
      driver0.setNumberOfReviews((-1804));
      int int0 = driver0.getNumberOfReviews();
      assertEquals((-1804), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("^F #/", "Na~", "Na~", "", localDate0, 0.0, "Na~");
      driver0.setExp(890);
      int int0 = driver0.getExp();
      assertEquals(890, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("xrd)Uxo*e?-q\"T_!+", "4y/zV*>;9q0=eh", "xrd)Uxo*e?-q\"T_!+", "O<Lo}2!'H':WM]7\"K=", localDate0, 4.0, "xrd)Uxo*e?-q\"T_!+");
      driver0.addRating(0);
      int int0 = driver0.getExp();
      assertEquals(1, driver0.getNumberOfReviews());
      assertEquals((-4), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2004L);
      Driver driver0 = new Driver("T#-", (String) null, "!kR3HdT:J.!Z^", "!kR3HdT:J.!Z^", localDate0, 2004L, (String) null);
      driver0.setdeviation(2004L);
      double double0 = driver0.getDeviation();
      assertEquals(2004.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = "ht\\uIP\"";
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("K_+%|tt2ERD#n;h`01'", "R#hEiH2*Z*=mzYBj", "R#hEiH2*Z*=mzYBj", string0, localDate0, 3885.0, 3885.0, boolean0, 3885.0, arrayList0, 0, 3067.28212989, 4.0, "K_+%|tt2ERD#n;h`01'", (String) null, (-127.4));
      double double0 = driver0.getDeviation();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals("K_+%|tt2ERD#n;h`01'", driver0.getVehicle());
      assertEquals(3885.0, driver0.getRating(), 0.01);
      assertEquals((-127.4), double0, 0.01);
      assertEquals(3885.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String string0 = "ht\\uIP\"";
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("K_+%|tt2ERD#n;h`01'", "R#hEiH2*Z*=mzYBj", "R#hEiH2*Z*=mzYBj", string0, localDate0, 3885.0, 3885.0, boolean0, 3885.0, arrayList0, 0, 3067.28212989, 4.0, "K_+%|tt2ERD#n;h`01'", (String) null, (-127.4));
      String string1 = driver0.getCompany();
      assertEquals(3885.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals("K_+%|tt2ERD#n;h`01'", driver0.getVehicle());
      assertEquals((-127.4), driver0.getDeviation(), 0.01);
      assertEquals(3885.0, driver0.getTimeCompliance(), 0.01);
      assertNull(string1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Driver driver0 = new Driver("", "iy;1GB<ZA`Ka", "", "=Ou", localDate0, 5734.5988007, "");
      String string0 = driver0.getCompany();
      assertEquals(5734.5988007, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals("", string0);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Viagem de (", "Viagem de (", "Viagem de (", "Viagem de (", localDate0, 272.92869323694106, "Viagem de (");
      driver0.equals(driver0);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(272.92869323694106, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Boolean boolean0 = Boolean.FALSE;
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Driver driver0 = new Driver("<f6t+xRIhy-L", "", "\nVe\u00EDculo : ", "O61YA%rxWhg_Q", localDate0, 438.74256856681, "\nDesvio total : ");
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Trip trip0 = new Trip(6168, point2D_Double0, point2D_Double0, (Double) 0.0, (Double) point2D_Double0.y, localDate0, "lF/nJ", "lF/nJ", "s", 1, 0.0, point2D_Double0, (-1772.4), 90.5985130661, 0.0);
      arrayList0.add(trip0);
      Driver driver1 = new Driver("\nVe\u00EDculo : ", "\nN\u00FAmero de viagens :", "<f6t+xRIhy-L", (String) null, localDate0, (-2978.555), 0.0, boolean0, 997.549, arrayList0, 1, (-1199.399465), 0.0, "\nN\u00FAmero de classifica\u00E7\u00F5es : ", "\nDesvio total : ", 1.0);
      Driver driver2 = driver1.clone();
      assertEquals("\nN\u00FAmero de classifica\u00E7\u00F5es : ", driver2.getVehicle());
      assertEquals(0, driver2.getExp());
      assertEquals(1, driver2.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals("\nDesvio total : ", driver0.getCompany());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals("\nDesvio total : ", driver2.getCompany());
      assertEquals(997.549, driver2.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver1.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(1.0, driver2.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(438.74256856681, driver0.getTimeCompliance(), 0.01);
      assertEquals(1, driver1.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      Driver driver0 = new Driver("", "", "", "Driver", localDate0, (-1L), "");
      driver0.setNumberOfReviews((-1804));
      driver0.clone();
      assertEquals((-1804), driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Month month0 = Month.SEPTEMBER;
      LocalDate localDate0 = MockLocalDate.of((-1699), month0, 5);
      Driver driver0 = new Driver((String) null, "", "\nMatr\u00EDcula ve\u00EDculo : ", "\neMail : ", localDate0, (-1699), (String) null);
      driver0.addRating(293);
      driver0.clone();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("", "", "h:", "", localDate0, 399.615066471907, "");
      driver0.setExp((-229));
      driver0.clone();
      assertEquals((-229), driver0.getExp());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = "ht\\uIP\"";
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("K_+%|tt2ERD#n;h`01'", "R#hEiH2*Z*=mzYBj", "R#hEiH2*Z*=mzYBj", string0, localDate0, 3885.0, 3885.0, boolean0, 3885.0, arrayList0, 0, 3067.28212989, 4.0, "K_+%|tt2ERD#n;h`01'", (String) null, (-127.4));
      Driver driver1 = driver0.clone();
      assertEquals(0, driver1.getExp());
      assertEquals(3885.0, driver1.getTimeCompliance(), 0.01);
      assertEquals(3885.0, driver1.getRating(), 0.01);
      assertEquals(3885.0, driver0.getRating(), 0.01);
      assertEquals("K_+%|tt2ERD#n;h`01'", driver1.getVehicle());
      assertEquals(3885.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals((-127.4), driver0.getDeviation(), 0.01);
      assertEquals((-127.4), driver1.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("", "", "h:", "", localDate0, 399.615066471907, "");
      // Undeclared exception!
      try { 
        driver0.setAvailability((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2004L);
      Driver driver0 = new Driver("T#-", (String) null, "!kR3HdT:J.!Z^", "!kR3HdT:J.!Z^", localDate0, 2004L, (String) null);
      Trip trip0 = new Trip();
      // Undeclared exception!
      try { 
        driver0.addTrip(trip0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver("\nVe\u00EDculo : ", "", "?ic4wT_@", "J>R*!lRq|", (LocalDate) null, 252.1698301932, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver((Driver) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "?6B!Yd+e0#noJ;46", "Uwb}$ i", localDate0, (-1.0), (-1.0), boolean0, 0.0, arrayList0, 0, 0.0, 0.0, "a5,Qx8!hJWgiZg", "", 1716.2308);
      Double double0 = driver0.getRating();
      assertEquals("", driver0.getCompany());
      assertEquals("a5,Qx8!hJWgiZg", driver0.getVehicle());
      assertEquals(1716.2308, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals((-1.0), (double)double0, 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      String string0 = "\\uKA$}Y\\=w50C:X_$hi";
      Driver driver0 = new Driver("Viagem de (", "Viagem de (", "lF/nJ", "\nVe\u00EDculo : ", localDate0, 269.417650127939, string0);
      double double0 = driver0.getDeviation();
      assertEquals(0.0, double0, 0.01);
      assertEquals("\\uKA$}Y\\=w50C:X_$hi", driver0.getCompany());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(269.417650127939, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("^F #/", "Na~", "Na~", "", localDate0, 0.0, "Na~");
      Driver driver1 = new Driver(driver0);
      assertTrue(driver1.isAvailable());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver1.getExp());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals("Na~", driver1.getCompany());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      String string0 = "\\uKA$}Y\\=w50C:X_$hi";
      Driver driver0 = new Driver("Viagem de (", "Viagem de (", "lF/nJ", "\nVe\u00EDculo : ", localDate0, 269.417650127939, string0);
      String string1 = driver0.getCompany();
      assertEquals("\\uKA$}Y\\=w50C:X_$hi", string1);
      
      Boolean boolean0 = Boolean.FALSE;
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Driver driver1 = new Driver("\nVe\u00EDculo : ", string1, "", "", localDate0, 0, (-2978.555), boolean0, 0, arrayList0, 0, (-1772.4), (-2978.555), (String) null, "lF/nJ", 0);
      boolean boolean1 = driver0.equals(driver1);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertFalse(boolean1);
      assertEquals((-2978.555), driver1.getRating(), 0.01);
      assertEquals("lF/nJ", driver1.getCompany());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver1.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(0.0, driver1.getTimeCompliance(), 0.01);
      assertEquals(269.417650127939, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("xrd)Uxo*e?-q\"T_!+", "4y/zV*>;9q0=eh", "xrd)Uxo*e?-q\"T_!+", "O<Lo}2!'H':WM]7\"K=", localDate0, 4.0, "xrd)Uxo*e?-q\"T_!+");
      int int0 = driver0.getNumberOfReviews();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, int0);
      assertEquals("xrd)Uxo*e?-q\"T_!+", driver0.getCompany());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(4.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("xrd)Uxo*e?-q\"T_!+", "4y/zV*>;9q0=eh", "xrd)Uxo*e?-q\"T_!+", "O<Lo}2!'H':WM]7\"K=", localDate0, 4.0, "xrd)Uxo*e?-q\"T_!+");
      int int0 = driver0.getExp();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, int0);
      assertEquals("xrd)Uxo*e?-q\"T_!+", driver0.getCompany());
      assertEquals(4.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("xrd)Uxo*e?-q\"T_!+", "=#8?R1#+Tt7A;;Px", "xrd)Uxo*e?-q\"T_!+", "O<Lo}2!'H':WM]7\"K=", localDate0, 4.0, "xrd)Uxo*e?-q\"T_!+");
      driver0.getVehicle();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals("xrd)Uxo*e?-q\"T_!+", driver0.getCompany());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(4.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("u|+q#", "u|+q#", "u|+q#", "u|+q#", localDate0, 4.0, "u|+q#");
      Boolean boolean0 = driver0.isAvailable();
      assertTrue(boolean0);
      
      driver0.setAvailability(boolean0);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(4.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      String string0 = "\\uKA$}Y\\=w50C:X_$hi";
      Driver driver0 = new Driver("Viagem de (", "Viagem de (", "lF/nJ", "\nVe\u00EDc~lo H ", localDate0, 269.4176501, string0);
      // Undeclared exception!
      try { 
        driver0.equals((Driver) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver();
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for MonthOfYear (valid values 1 - 12): 0
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("u|+q#", "u|+q#", "u|+q#", "u|+q#", localDate0, 4.0, "u|+q#");
      String string0 = driver0.toString();
      assertEquals("Driver \nUtilizador - u|+q#\neMail : u|+q#\nPassword : u|+q#\nMorada : u|+q#\nData de nascimento : 2014-02-14\nDist\u00E2ncia Total : 0.0\nDinheiro gasto/ganho : 0.0\nN\u00FAmero de viagens :0\nDisponibilidade : true\nClassifica\u00E7\u00E3o : 0.0\nGrau de cumprimento : 4.0\nN\u00FAmero de classifica\u00E7\u00F5es : 0\nVe\u00EDculo : null\nDesvio total : 0.0\n", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver(".", ".", "\nN\u00FAmero de classifica\u00E7\u00F5es : ", ".", localDate0, 0.0, "f92U'H!U/YBQ[QjgV");
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Driver driver1 = null;
      try {
        driver1 = new Driver("\nGrau de cumprimento : ", "\nGrau de cumprimento : ", "s", "", localDate0, 4.0, 3600.0, (Boolean) null, 0.0, arrayList0, 0, 0.0, 0.0, "xXP7#}An!", "f92U'H!U/YBQ[QjgV", (-3946.8542258));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Driver", e);
      }
  }

}
