/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 21:19:00 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MoneyComparatorD_ESTest extends MoneyComparatorD_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("syCN)YMi19Q>\"4$f}", "q", "[GwQ(wdP;[SDU|7*", "", localDate0, 1280.2099, "");
      Driver driver1 = new Driver(driver0);
      int int0 = moneyComparatorD0.compare(driver0, driver1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      // Undeclared exception!
      try { 
        moneyComparatorD0.compare((Driver) null, (Driver) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MoneyComparatorD", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = Boolean.TRUE;
      Driver driver0 = new Driver("@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", localDate0, 184L, 184L, boolean0, 184L, (ArrayList<Trip>) null, (-1194), 184L, 184L, "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", 184L);
      Driver driver1 = new Driver("@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", localDate0, 0, "@2}`59Q1Pk4zM8PO");
      int int0 = moneyComparatorD0.compare(driver1, driver0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = Boolean.TRUE;
      Driver driver0 = new Driver("@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", localDate0, 184L, 184L, boolean0, 184L, (ArrayList<Trip>) null, (-1194), 184L, 184L, "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", 184L);
      Driver driver1 = new Driver("@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", "@2}`59Q1Pk4zM8PO", localDate0, 0, "@2}`59Q1Pk4zM8PO");
      int int0 = moneyComparatorD0.compare(driver0, driver1);
      assertEquals((-1), int0);
  }
}
